services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8079:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet
  exporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    ports:
      - "9113:9113"
    environment:
      - SCRAPE_URI=http://nginx:8080/stub_status
    networks:
      - webnet
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet
networks:
  webnet:
